name: CI/CD

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with: 
          ruby-version: 2.7.2

      - name: Install SQLite3
        run: sudo apt install libsqlite3-dev

      - name: Cache Ruby Gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gems-
      
      - name: Install Ruby Gems
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          
      - name: Install yarn packages
        run: yarn install --check-files
      
      - name: Setup Database
        run: bundle exec rails db:setup
      
      - name: Run Tests
        run: bundle exec rspec .

  Deployment:
    needs: CI # assures, that the job "CI" completed successful before this job is started
    runs-on: ubuntu-latest

    # The both deployment steps contain two safeguards.
    # github.event_name == 'push' assures that the pull requests, for which the CI should run too, are not deployed to Heroku
    # github.ref == 'refs/heads/<branch name>' assures that in the current step, only one of the branches is deployed. 
    #   This was made because the two different deployments (main and dev) each have their own Heroku-App.

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy Main Branch to Heroku
        env:
          HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
          HEROKU_APP_NAME: 'connections-portal-main'
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: git push https://heroku:$HEROKU_API_TOKEN@git.heroku.com/$HEROKU_APP_NAME.git origin/main:main

      - name: Deploy Dev Branch to Heroku
        env:
          HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
          HEROKU_APP_NAME: 'connections-portal-dev'
        if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
        run: git push https://heroku:$HEROKU_API_TOKEN@git.heroku.com/$HEROKU_APP_NAME.git origin/dev:dev
